BlogApp/urls.py
from django.urls import path
import BlogApp.views
from .views import NewBlogPostView

app_name = 'BlogApp'

urlpatterns = [

    # /BlogApp/
    path('', BlogApp.views.BlogView.as_view(), name='all_posts'),

    # /BlogApp/<post_id>/
    path('<int:pk>/', BlogApp.views.PostView.as_view(), name='post-detail'),

    path('new_post/', BlogApp.views.NewBlogPostView.as_view(), name='new_post'),

    path('<int:pk>/comment/', BlogApp.views.CommentCreate.as_view(), name='comment'),

]

My_Songs/urls.py
from django.urls import path
import My_Songs.views


app_name = 'My_Songs'  # Separate 'detail' 'index' and other patterns in between apps (My_Songs:detail)

urlpatterns = [
    # /My_Songs/
    path('', My_Songs.views.TemplateView.as_view(), name='index'),

    # /My_Songs/album_page/
    path('album_page/', My_Songs.views.AlbumView.as_view(), name='album_page'),

    # /My_Songs/<album_id>/
    path('<int:pk>/', My_Songs.views.DetailView.as_view(), name='detail'),

    # /My_Songs/all_songs/
    path('songs/', My_Songs.views.all_songs, name='all_songs'),

    # /My_Songs/add_song/
    path('add/', My_Songs.views.SongCreate.as_view(), name="add-song"),

    # /My_Songs/<song_id>/updates/
    path('<int:pk>/update/', My_Songs.views.SongUpdate.as_view(), name="update-song"),

    # /My_Songs/<song_id>/delete_song/
    path('<int:pk>/delete/', My_Songs.views.SongDelete.as_view(), name="delete-song"),

    # /My_Songs/aboutme/
    path('aboutme_page/', My_Songs.views.AboutMeView.as_view(), name="about-me"),


]

test1_tutorial/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('My_Songs/', include('My_Songs.urls')),
    path('BlogApp/', include('BlogApp.urls')),
    path('register/', views.UserFormView.as_view(), name='register'),
    path('login/', views.UserLoginView.as_view(), name='login'),
    path('user/logout/', views.logout_view, name='logout'),
    path('user/', views.UserPageView.as_view(), name='user'),
    # path('update/', views.UpdateProfileView.as_view(), name='update')
]

My_Songs/models.py
from django.db import models
from django.urls import reverse

# Sets up DB entries/structure


class Album(models.Model):
    artist = models.CharField(max_length=250)
    album_title = models.CharField(max_length=250)
    genre = models.CharField(max_length=250)
    album_logo = models.CharField(max_length=1000)
    album_description = models.CharField(max_length=10000, null=True, blank=True)

    def get_absolute_url(self):
        return reverse('My_Songs:detail', kwargs={'pk': self.pk})

    def __str__(self):
        return self.album_title + ' by ' + self.artist


class Song(models.Model):
    album = models.ForeignKey(Album, on_delete=models.CASCADE)  # Relates albums and songs
    file_type = models.CharField(max_length=10)
    song_title = models.CharField(max_length=250)
    song_link = models.CharField(max_length=1000, null=True, blank=True)
    song_description = models.CharField(max_length=10000, null=True, blank=True)

    def get_absolute_url(self):
        return reverse('My_Songs:detail', kwargs={'pk': self.album.pk})

    def __str__(self):
        return self.song_title

My_Songs/views.py
from django.shortcuts import render, get_object_or_404
from .models import Album, Song
from django.views import generic
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy


# Second+ arguments have to match '<str:album_page>/' parameter in path, which is set in urls.py

class TemplateView(generic.TemplateView):
    template_name = 'My_Songs/homepage.html'


# Display all songs - Not sure why 'all_songs' is needed as a parameter
def all_songs(request):
    all_albums = Album.objects.all()  # Get all albums
    return render(request, 'My_Songs/songs.html', {'all_albums': all_albums})


class AlbumView(generic.ListView):
    template_name = 'My_Songs/album_page.html'
    context_object_name = 'all_albums'

    def get_queryset(self):
        return Album.objects.all()


class DetailView(generic.DetailView):
    model = Album
    template_name = 'My_Songs/detail.html'


class SongCreate(CreateView):
    model = Song
    context_object_name = 'song'
    fields = ['album', 'song_title', 'song_link', 'song_description']


class SongUpdate(UpdateView):
    model = Song
    fields = ['album', 'song_title', 'song_link', 'song_description']


class SongDelete(DeleteView):
    model = Song
    success_url = reverse_lazy('My_Songs:index')


class AboutMeView(generic.TemplateView):
    template_name = 'My_Songs/aboutme_page.html'

My_Songs/templates/My_Songs/aboutme_page.html
<head>
{% extends 'base.html' %}

    {% load staticfiles %}
    {% block css %}
        <link rel="stylesheet" type="text/css" href="{% static 'My_Songs\aboutme.css' %}"/>
    {% endblock %}

{% block title %} About Me {% endblock %}

    <script type="text/javascript">

        function changeImg(){
            document.getElementByClassName("img-rounded").src = images[x];
            x = (x + 1) % x;
        }

        function imgTimer(){
            setInterval(changeImg, 300);
        }

        var images = [], x = 0;
        images[0] = "https://scontent-iad3-1.xx.fbcdn.net/v/t1.0-9/12313677_1096354523731269_8616707537810682270_n.jpg?_nc_cat=0&oh=b1c45a1bf023987f4e4edaada35ebe0f&oe=5BD649B5";
        images[1] = "https://scontent-iad3-1.xx.fbcdn.net/v/t1.0-9/31659917_1663797473697043_6064904261911707648_o.jpg?_nc_cat=0&oh=44d51e1733812684d546bdc099c1a107&oe=5C0F1CBC";
        images[2] = "https://scontent-iad3-1.xx.fbcdn.net/v/t1.0-9/18893437_480097902333574_8912007922953234888_n.jpg?_nc_cat=0&oh=57c49522bce147728c586009f9df2dc8&oe=5C0F61FD";
        images[3] = "https://scontent-iad3-1.xx.fbcdn.net/v/t1.0-9/12804896_1147874438579277_3378301262197219096_n.jpg?_nc_cat=0&oh=87d288f3cd1929c6e598ec570796b11f&oe=5BD554C6";

    </script>

</head>
{% block body %}

    <body onload="imgTimer()">

        <img id="me-img" class="img-circle" src="https://scontent-iad3-1.xx.fbcdn.net/v/t1.0-9/12313677_1096354523731269_8616707537810682270_n.jpg?_nc_cat=0&oh=b1c45a1bf023987f4e4edaada35ebe0f&oe=5BD649B5" style="width:100%">
        <div id="flex-container">
            <div id="row">
                <div id="col-md-4 col-md-offset-4">
                    <h2 style="color:darkgrey">Hi, I'm Owen Carpenter.</h2>
                    <p>I'm a 20 year old Computer Science student at the University of Massachusetts Amherst.
                        Growing up, I was always interested in computers - whether it was for gaming, video creation, or music creation.
                        When it came time to decide what I wanted to study for college, Computer Science didn't come to me immediately.
                        For some reason, I didn't even realize it was an option. However, as soon as my dad pointed it out to me,
                        I was all for it.
                    </p>
                    <br>
                    <p>So far, CompSci has pushed me and caused me to grow in ways I couldn't have ever imagined for myself just a few years ago.
                        I've only just begun to break the surface with computers and programming, but already the vastness of the subject
                        amazes me every time I think about it. Although programming is my preference when it comes to my studies, the
                        benefits of understanding the low level hardware and theories of computation can not be denied.
                    </p>
                    <br>
                    <h3 style="color:darkgrey">Outside of school and my studies, I like to consider myself a musician, athlete, and gamer.</h3>
                     <br>
                    <p>
                        I have dedicated a lot of time over the past four years to studying the guitar and learning as much about it as I can. I can proudly say that it has been
                        the most beneficial undertaking in my life, as it has opened my ears up to so much different music, and caused my to open
                        my perspectives up to avenues of life that I would have never given a shot before.
                    </p>
                     <br>
                    <p>
                        I also like to frequent the gym. I highly recommend (and have been religiously following) Jim Wendler's 5/3/1 program. I can't recommend it enough.
                        The strength gains and simplicity of the program are not to be ignored.
                    </p>
                    <br>
                    <p>
                        And after everything else in my typical day has wrapped up, I usually find myself in front of my monitor, playing video games with my
                        longtime group of friends. I have had an interest in this type of content creation (both game development and gameplay recording) for a long time,
                        and have even recorded and released some videos on Youtube when I was younger. As time goes forward, I would love to start streaming the games I play
                        by myself and with my friends, to archive our idiocy throughout the years.
                    </p>
                </div>
            </div>

            <div class="row">
              <div class="col-md-4">
                  <h4 style="color:black">You can contact me at:</h4>
                  <h5 style="color:black">owenc343@gmail.com</h5>
                  <h5 style="color:black">ocarpenter@umass.edu</h5>
              </div>
            </div>

        </div>


    </body>

{% endblock %}

My_Songs/templates/My_Songs/album_page.html
{% extends 'base.html' %}

{% block title %} Albums {% endblock %}

{% block body %}

    <body>

        {% if all_albums %}

            {%for album in all_albums%}

                <div class="container-fluid" style="margin-top:75px">
                    <div class="col-md-4">
                        <img class="img-rounded" src = "{{ album.album_logo }}" width="255" height="180" />
                        <h3><a href = "{% url 'My_Songs:detail' album.id %}">{{ album.album_title }}</a></h3>
                    </div>
                </div>

            {% endfor %}



            {% else %}
                <h3>What, do you hate music?</h3>

        {% endif %}

    </body>

{% endblock %}

My_Songs/templates/My_Songs/detail.html
{% extends 'base.html' %}

{% block title %} {{ album.album_title}}  {% endblock %}

{% load staticfiles %}
{% block css %}
    <link rel="stylesheet" type="text/css" href="{% static 'My_Songs/detail.css' %}"/>
{% endblock %}

{% block body %}

    <center>

        <div class="container-fluid">
            <img src = "{{ album.album_logo }}"/>
            <div class="centered"><h2>{{ album.album_title }}</h2> </div>
            <div class="bottom-centered"><h3>{{ album.artist }}</h3> </div>
        </div>

        {% if error_message %}
            <p><strong>{{ error_message }}</strong></p>
        {% endif %}

            <div class="row">
                <div class="col-md-2 col-md-offset-10" style="color:black">
                    <button class="btn btn-info btn-md"><a href="{% url 'My_Songs:add-song' %}">Add Song</a></button>
                </div>
            </div>

            {% csrf_token %}
            {% for song in album.song_set.all %}

            <ul style="color:lightgrey">
                {% if song.song_link != null %}
                    <iframe width="50%" height="100" scrolling="no" frameborder="no" allow="autoplay" src="{{ song.song_link }}"></iframe>
                {% else %}
                    {{song.song_title}}
                {% endif %}
                <button class="btn btn-success"><a href="{% url 'My_Songs:update-song' song.id %}">Edit</a></button>
                <button class="btn btn-danger"><a href="{% url 'My_Songs:delete-song' song.id %}">Delete</a></button>
            </ul>

            {% endfor %}

        </form>

    </center>

{% endblock %}

My_Songs/templates/My_Songs/homepage.html
<head>

    {% extends 'base.html' %}


    {% load staticfiles %}
    {% block css %}
        <link rel="stylesheet" type="text/css" href="{% static 'My_Songs/homepage.css' %}" id="style"/>
    {% endblock %}
    {% block title %} Djangoland {% endblock %}

</head>

{% block body %}

<body class="content" style="background-image:url(https://scontent-iad3-1.xx.fbcdn.net/v/t1.0-9/12274584_1096353490398039_2194026952118303127_n.jpg?_nc_cat=0&oh=49a2e6388b1e19956d5914eb019b3404&oe=5B771D14);">



    <div class="container-fluid">

        <div class="row" id="logo" >

            <div class="col-sm-3">
                <img src="https://imgur.com/offI8aN.jpg" class="img-responsive" style="margin-left:20px; height:120px; width:213px">

                <!--<img class="img-circle"-->
                     <!--src="https://scontent-iad3-1.xx.fbcdn.net/v/t1.0-9/12274584_1096353490398039_2194026952118303127_n.jpg?_nc_cat=0&oh=49a2e6388b1e19956d5914eb019b3404&oe=5B771D14" width="230" height="250">-->
            </div>
        </div>

        <div class="row" style="vertical-align:middle; margin-left:-13px; margin-top:7px">
            <!--<div class="col-sm-3">-->
                <!--<a href="https://www.facebook.com/owen.carpenter.50?ref=bookmarks" target="_blank"><i  id="fb-logo" class="fa fa-facebook-square"></i></a>-->
                <!--<a href="https://www.youtube.com/channel/UCpKvmRgD_AFG4b534sG0nXA?view_as=subscriber" target="_blank"><i id="yt-logo" class="fa fa-youtube-square"></i></a>-->
                <!--<a href="https://twitter.com/Unfold_Reality" target="_blank"><i id="twitter-logo" class="fa fa-twitter"></i></a>-->
                <!--<a href="https://github.com/oFrusch" target="_blank"><i id="gh-logo" class="fa fa-github" style="font-size: 32px; color: #6e5494; margin-left: 30px; margin-top: 5px;"></i></a>-->
            <!--</div>-->
        </div>


        <div class="row" style="vertical-align:middle; margin-left:7px;">
            <div class="col-xs-3">
                <!--<h4 style="color:white">Email: </h4>-->
                <!--<h5 style="color:white">owenc343@gmail.com</h5>-->
            </div>

            <div class="col-sm-8">
                <h1>Owen Carpenter</h1>
                <h3>Computer Science Student at UMass Amherst</h3>
                <h3>Intern at Cisco Systems</h3>
                <h3>Musician</h3>
                <h3>Gamer</h3>
            </div>
        </div>

    </div>

</body>

{% endblock %}

My_Songs/templates/My_Songs/song_confirm_delete.html
{% extends 'base.html' %}

{% block body %}

<body>

    <div class="container-fluid">
        <div class="row">
            <div class="col-md-6 col-md-offset-4">
                <h3 style="color:darkgrey">Are you sure you want to delete "{{ object }}"?</h3>

            </div>
        </div>
        <div class="row">
            <div class="col-md-6 col-md-offset-5">
                <form action="" method="post">{% csrf_token %}
                    <button class="btn btn-success" type="submit" value="Confirm" onclick="delete()">Confirm</button>
                    <button class="btn btn-danger">Cancel</button>
                </form>
            </div>
        </div>
    </div>

</body>

{% endblock %}

My_Songs/templates/My_Songs/song_form.html
<head>

    {% extends 'base.html' %}

    {% block title %} Add Song {% endblock %}

</head>

{% block body %}

    <body>
        <div class="container-fluid">
            <div class="row">
                <div class="col-sm-12 col-md-7">
                    <div class="panel-body">
                        <form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
                            {% csrf_token %}

                            {% include 'My_Songs/form-template.html' %}

                            <div class="form-group">
                                <div class="col-sm-offset-2 col-sm-10">
                                    <button type="submit" class="btn btn-success">Submit</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>



    </body>

{% endblock %}

My_Songs/templates/My_Songs/songs.html
{% extends 'base.html' %}

{% block title %} All Songs {% endblock %}

{% block body %}



        {% csrf_token %}

        {% for album in all_albums %}
            <h4 style="margin-left:25px">{{ album.album_title }}</h4>
            {% for song in album.song_set.all %}
                 <ul>
                    {% if song.song_link != null %}
                        <a href = "{{ song.song_link }}" target="_blank">{{song.song_title}}</a>
                    {% else %}
                        {{song.song_title}}
                    {% endif %}
                </ul>
            {% endfor %}
        {% endfor %}



{% endblock %}