BlogApp/urls.py
from django.urls import path
import BlogApp.views
from .views import NewBlogPostView

app_name = 'BlogApp'

urlpatterns = [

    # /BlogApp/
    path('', BlogApp.views.BlogView.as_view(), name='all_posts'),

    # /BlogApp/<post_id>/
    path('<int:pk>/', BlogApp.views.PostView.as_view(), name='post-detail'),

    path('new_post/', BlogApp.views.NewBlogPostView.as_view(), name='new_post'),

    path('<int:pk>/comment/', BlogApp.views.CommentCreate.as_view(), name='comment'),

]

My_Songs/urls.py
from django.urls import path
import My_Songs.views


app_name = 'My_Songs'  # Separate 'detail' 'index' and other patterns in between apps (My_Songs:detail)

urlpatterns = [
    # /My_Songs/
    path('', My_Songs.views.TemplateView.as_view(), name='index'),

    # /My_Songs/album_page/
    path('album_page/', My_Songs.views.AlbumView.as_view(), name='album_page'),

    # /My_Songs/<album_id>/
    path('<int:pk>/', My_Songs.views.DetailView.as_view(), name='detail'),

    # /My_Songs/all_songs/
    path('songs/', My_Songs.views.all_songs, name='all_songs'),

    # /My_Songs/add_song/
    path('add/', My_Songs.views.SongCreate.as_view(), name="add-song"),

    # /My_Songs/<song_id>/updates/
    path('<int:pk>/update/', My_Songs.views.SongUpdate.as_view(), name="update-song"),

    # /My_Songs/<song_id>/delete_song/
    path('<int:pk>/delete/', My_Songs.views.SongDelete.as_view(), name="delete-song"),

    # /My_Songs/aboutme/
    path('aboutme_page/', My_Songs.views.AboutMeView.as_view(), name="about-me"),


]

test1_tutorial/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('My_Songs/', include('My_Songs.urls')),
    path('BlogApp/', include('BlogApp.urls')),
    path('register/', views.UserFormView.as_view(), name='register'),
    path('login/', views.UserLoginView.as_view(), name='login'),
    path('user/logout/', views.logout_view, name='logout'),
    path('user/', views.UserPageView.as_view(), name='user'),
    # path('update/', views.UpdateProfileView.as_view(), name='update')
]

BlogApp/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from django.utils import timezone


class BlogPost(models.Model):
    title = models.CharField(max_length=100)
    post = models.TextField(max_length=10000)
    link = models.URLField(max_length=1000, null=True, blank=True)
    img = models.URLField(max_length=1000, null=True, blank=True)
    date_added = models.CharField(max_length=20, null=True, blank=True)
    liked = models.BooleanField(default=False)

    def __str__(self):
        return self.title


class Comment(models.Model):
    post = models.ForeignKey(BlogPost, null=True, on_delete=models.CASCADE)  # Relates Comment with BlogPost
    commenter = models.ForeignKey(User, null=True, on_delete=models.CASCADE)
    date = models.DateTimeField('Date Posted', default=timezone.now)
    comment = models.TextField(max_length=2000)

    def get_absolute_url(self):
        return reverse('BlogApp:all_posts')

    def __str__(self):
        return self.comment

BlogApp/forms.py
from django import forms
from .models import BlogPost, Comment


class BlogPostForm(forms.ModelForm):

    class Meta:
        model = BlogPost
        fields = ['title', 'post', 'date_added', 'img']


class CommentPostForm(forms.ModelForm):

    class Meta:
        model = Comment
        fields = ['comment']

BlogApp/views.py
from django.contrib.auth.models import User

from BlogApp.models import BlogPost
from django.views import generic
from django.shortcuts import render, redirect
from django.views.generic import View
from .forms import BlogPostForm, CommentPostForm
from django.views.generic.edit import CreateView
from .models import Comment


class BlogView(generic.ListView):
    template_name = 'Blog/all_posts.html'
    context_object_name = 'all_posts'

    def get_queryset(self):
        return BlogPost.objects.order_by('-id')


class PostView(generic.DetailView):
    model = BlogPost
    template_name = 'Blog/post.html'
    context_object_name = 'post'


class NewBlogPostView(View):
    template_name = 'Blog/new_post.html'
    form_class = BlogPostForm

    def get(self, request):
        form = self.form_class(None)
        return render(request, self.template_name, {'form': form})

    def post(self, request):
        form = self.form_class(request.POST)

        if form.is_valid():
            post = form.save(commit=False)
            post.save()
            return redirect('BlogApp:all_posts')

        return render(request, self.template_name, {'form': form})


class CommentCreate(CreateView):
    template_name = "Blog/comment_form.html"
    model = Comment
    context_object_name = 'comment'
    fields = ['post', 'comment', 'commenter']





    # if form.is_valid():
    #     form.save()
    # else:
    #     form = BlogPostForm()
    #
    # context = {
    #     'form': form,
    # }
    # return render(request, template, context)

BlogApp/templates/Blog/all_posts.html
<head>

    {% extends 'base.html' %}

    {% load staticfiles %}
    {% block css %}
        <link rel="stylesheet" type="text/css" href="{% static 'BlogApp\blog_page.css' %}"/>
    {% endblock %}

    {% block title %} All Posts {% endblock %}
    {{ post.value | linebreaksbr }}
</head>

{% block body %}

    <body class="scroll-area" data-spy="scroll" data-target=".navbar" data-offset="50">

        <div class="row">
            <div class="col-md-2 col-md-offset-10" style="color:black">
                <button class="btn btn-info btn-md"><a href="new_post/">Add New Blog Post</a></button>
            </div>
        </div>
         {% if all_posts %}

            {% for post in all_posts %}

                <div class="flex-container" id="spyOnThis">
                    <div class="row">
                        <div class="col-md-6 col-md-offset-3" id="main-content">
                            <h4 style="color:#75CEEA">{{ post.title }}</h4>
                            {% if post.date_added %}
                                <span style="color:grey">{{ post.date_added }}</span>
                            {% endif %}
                            {% if post.img %}
                                <img src="{{post.img}}" class="img-rounded">
                            {% endif %}

                            <p id="post" style="color:black">{{ post.post|linebreaksbr }} </p>

                            <div class="row">
                                <div class="col-md-11 col-md-offset-1">
                                    <h4 style="color:#75CEEA">Comments</h4>
                                    {% for comment in post.comment_set.all %}
                                        {{ comment.commenter }}
                                        <p style="border:1px; border-style:solid; border-color:lightgrey; color:black">
                                            {{ comment.comment }}
                                            <br>
                                            <div class="col-md-12 col-md-offset-0">
                                                <h6>{{ comment.date }}</h6>
                                            </div>
                                        </p>
                                    {% endfor %}
                                </div>
                            </div>

                            <br>

                            <a href="{% url 'BlogApp:comment' post.id %}">Add Comment</a>
                        </div>
                    </div>
                </div>

            {% endfor %}

         {% else %}
            <h3>Post Unavailable</h3>

         {% endif %}

    </body>

{% endblock %}

BlogApp/templates/Blog/base.html
<!DOCTYPE html>
<html lang="en">
<head>

    <meta charset="UTF-8">

     <!-- Load Bootstrap -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">

     <!-- Loads CSS styling -->
    {% load staticfiles %}
    <link rel="stylesheet" type="text/css" href="{% static 'My_Songs/style.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'My_Songs/homepage.css' %}" />


    <!-- Font -->
    <link href="https://fonts.googleapis.com/css?family=Quicksand" rel="stylesheet">

</head>

<body>

    <title>{% block title %} My Music {% endblock %}</title>

    <nav class="navbar navbar-inverse">

        <div class="container-fluid">

            <!-- Header -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                    <span class="glyphicon glyphicon-menu-down"></span>
                    <span class="glyphicon glyphicon-menu-down"></span>
                    <span class="glyphicon glyphicon-menu-down"></span>
                </button>
                <a class="navbar-brand" href="{% url 'My_Songs:index' %}">Djangoland</a>
            </div>

            <!-- Header Items -->
            <div class="collapse navbar-collapse" id="topNavBar">
                <ul class="nav navbar-nav">
                    <li class="">
                        <a href="/My_Songs/album_page/">
                            <span class="glyphicon glyphicon-cd" aria-hidden="true"></span>&nbsp; Albums
                        </a>
                    </li>
                    <li class="">
                        <a href="/My_Songs/songs/">
                            <span class="glyphicon glyphicon-user" aria-hidden="true"></span>&nbsp; About Me
                        </a>
                    </li>
                    <li class="">
                        <a href="https://www.youtube.com/channel/UCpKvmRgD_AFG4b534sG0nXA?view_as=subscriber" target="_blank">
                            <span class="glyphicon glyphicon-envelope" aria-hidden="true"></span>&nbsp; Contact
                        </a>
                    </li>
                    <li class="">
                        <a href="#">
                            <span class="glyphicon glyphicon-book" aria-hidden="true"></span>&nbsp; Blog
                        </a>
                    </li>
                </ul>

                <form class ="navbar-form navbar-right" role="search" method="get" action="">
                    <div>
                        <a href="https://www.facebook.com/owen.carpenter.50?ref=bookmarks" target="_blank"><i class="fa fa-facebook-square" style="font-size:32px; color:#3B5998; margin-left:23px; margin-bottom:20px"></i></a>
                        <a href="https://www.youtube.com/channel/UCpKvmRgD_AFG4b534sG0nXA?view_as=subscriber" target="_blank"><i class="fa fa-youtube-square" style="font-size:32px; color:#e52d27; margin-left:33px; margin-top:5px"></i></a>
                        <a href="https://twitter.com/Unfold_Reality" target="_blank"><i class="fa fa-twitter" style="font-size:32px; color:#00aced; margin-left:30px; margin-top:5px"></i></a>
                        <a href="https://github.com/oFrusch" target="_blank"><i class="fa fa-github" style="font-size:32px; color:#6e5494; margin-left:30px; margin-top:5px"></i></a>
                        <a href="https://www.twitch.tv/odjangolicious" target="_blank"><i class="fa fa-twitch" style="font-size:32px; color:#6441a5; margin-left:30px; margin-top:5px"></i></a>
                        <a href="https://soundcloud.com/owen-carpenter-2/" target="_blank"><i class="	fa fa-soundcloud" style="font-size:32px; color:#ff8800; margin-left:30px; margin-top:5px"></i></a>
                    </div>
                </form>

            </div>

            <!-- Header Search Bar -->
            <!--<form class ="navbar-form navbar-right" role="search" method="get" action="">-->
                <!--<div class = "form-group">-->
                    <!--<input type="text" class="form-control" name="q" value="">-->
                <!--</div>-->
                <!--<button type="submit" class="btn btn-default">Search</button>-->
            <!--</form>-->




        </div>
    </nav>


    {% block body %}


    {% endblock %}

</body>


</html>

BlogApp/templates/Blog/comment_form.html
<!DOCTYPE html>

<head>

    {% extends 'base.html' %}

    {% block title %} Add Comment {% endblock %}

</head>

<body>

{% block body %}



<div class="col-md-offset-3 col-md-6" style="color:darkgrey">
        <form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
            <div class="row">
                <div class="form-group">
                    {% csrf_token %}

                    {% with comment.commenter as user.username %}

                    {% endwith %}
                    {% include 'form-template.html' %}
                </div>
            </div>
            <div class="row">
                <div class="col-md-10 col-md-offset-2">
                    <button type="submit">Submit</button>
                </div>
            </div>
        </form>

</div>

{% endblock %}

</body>

BlogApp/templates/Blog/new_post.html
<!DOCTYPE html>

<head>

    {% extends 'base.html' %}

    {% block title %} New Blog Post {% endblock %}

</head>

<body>

{% block body %}



<div class="col-md-offset-3 col-md-6" style="color:darkgrey">
        <form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
            <div class="row">
                <div class="form-group">
                    {% csrf_token %}
                    {% include 'form-template.html' %}
                </div>
            </div>
            <div class="row">
                <div class="col-md-10 col-md-offset-2">
                    <button type="submit">Submit</button>
                </div>
            </div>
        </form>

</div>

{% endblock %}

</body>

BlogApp/templates/Blog/post.html
{% extends 'base.html' %}

{% load staticfiles %}
<link rel="stylesheet" type="text/css" href="{% static 'BlogApp/posts.css' %}" />

{% block title %} {{ post.title }}  {% endblock %}

{% block body %}

<body>

    <center>
        <div class="container">

            <div class="row">
                <h1><bold>{{ post.title }}</bold></h1>

                {% if post.date_added %}
                    <span>{{ post.date_added }}</span>
                {% endif %}

                {% if post.img %}
                <img src="{{ post.img }}"
                    class="img-rounded">
                {% endif %}
            </div>

            <div class="row">
                <h3 style="color:lightgrey; margin-left:250px; margin-right:250px">{{ post.post }}</h3>
            </div>

            <div class="row">
                {% if post.link %}
                    <h3><a href="{{ post.link }}" target="_blank">You can find the project here.</a></h3>
                {% endif %}
            </div>

        </div>
    </center>

</body>

{% endblock %}